version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/productdb

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: productdb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
